# -*- coding: utf-8 -*-
"""support_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1calS8u55crtJRmp44JcI5CNrxyCx2A3r
"""

"""
PART 3 - FLIPKART SUPPORT AGENT
LangGraph-based support assistant.
"""

import os
import json
import pickle
import numpy as np
import torch

from PIL import Image
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import create_react_agent


BASE_DIR = os.path.dirname(os.path.abspath(__file__))

RETURN_MODEL_PATH = os.path.join(
    BASE_DIR,
    "models",
    "return_risk_model.pkl"
)

IMAGE_MODEL_PATH = os.path.join(
    BASE_DIR,
    "models",
    "product_classifier.pt"
)

POLICY_PATH = os.path.join(
    BASE_DIR,
    "knowledge_base",
    "policies.json"
)


print("Loading Part 1 return-risk model...")

if not os.path.exists(RETURN_MODEL_PATH):
    raise FileNotFoundError(
        f"Return-risk model not found: {RETURN_MODEL_PATH}"
    )

with open(RETURN_MODEL_PATH, "rb") as f:
    return_risk_model = pickle.load(f)

print("Part 1 model loaded successfully.")


print("Loading policy knowledge base...")

if not os.path.exists(POLICY_PATH):
    raise FileNotFoundError(
        f"Policy knowledge base not found: {POLICY_PATH}"
    )

with open(POLICY_PATH, "r", encoding="utf-8") as f:
    policies = json.load(f)

print(f"Loaded {len(policies)} policy documents.")


def search_policies(query, top_k=3):

    query_words = set(
        word.lower()
        for word in query.split()
        if len(word) > 2
    )

    scored_documents = []

    for document in policies:

        text = (
            document.get("title", "")
            + " "
            + document.get("content", "")
            + " "
            + " ".join(document.get("keywords", []))
        ).lower()

        score = sum(
            1 for word in query_words
            if word in text
        )

        if score > 0:
            scored_documents.append(
                (score, document)
            )

    scored_documents.sort(
        key=lambda x: x[0],
        reverse=True
    )

    return [
        document
        for _, document in scored_documents[:top_k]
    ]


@tool
def search_policy(query: str) -> str:

    results = search_policies(query)

    if not results:
        return (
            "No relevant policy document was found in the "
            "knowledge base. Do not invent a policy."
        )

    output = []

    for document in results:
        output.append(
            f"Document ID: {document.get('id', 'N/A')}\n"
            f"Title: {document.get('title', 'N/A')}\n"
            f"Content: {document.get('content', '')}"
        )

    return "\n\n".join(output)


@tool
def check_return_risk(
    category: str,
    price_inr: float,
    discount_pct: float,
    customer_tenure_days: int,
    num_previous_orders: int,
    num_previous_returns: int,
    delivery_distance_km: float,
    delivery_days: int,
    is_weekend_order: int,
    rating_given: float = np.nan,
    payment_method: str = "COD"
) -> str:

    input_data = {
        "category": category,
        "price_inr": price_inr,
        "discount_pct": discount_pct,
        "customer_tenure_days": customer_tenure_days,
        "num_previous_orders": num_previous_orders,
        "num_previous_returns": num_previous_returns,
        "delivery_distance_km": delivery_distance_km,
        "delivery_days": delivery_days,
        "is_weekend_order": is_weekend_order,
        "rating_given": rating_given,
        "payment_method": payment_method
    }

    try:

        import pandas as pd

        X = pd.DataFrame([input_data])

        prediction = return_risk_model.predict(X)[0]

        probability = None

        if hasattr(return_risk_model, "predict_proba"):
            probability = return_risk_model.predict_proba(X)[0][1]

        risk = "HIGH" if prediction == 1 else "LOW"

        if probability is not None:
            return (
                f"Return risk: {risk}\n"
                f"Estimated return probability: "
                f"{probability:.2%}"
            )

        return f"Return risk: {risk}"

    except Exception as e:

        return (
            "Unable to calculate return risk using the saved "
            f"model. Error: {str(e)}"
        )


PRODUCT_CLASSES = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot"
]


class ProductClassifier(torch.nn.Module):

    def __init__(self, num_classes=10):

        super().__init__()

        from torchvision.models import resnet18

        self.model = resnet18(
            weights=None
        )

        self.model.fc = torch.nn.Linear(
            self.model.fc.in_features,
            num_classes
        )

    def forward(self, x):
        return self.model(x)


print("Loading Part 2 image classifier...")

if not os.path.exists(IMAGE_MODEL_PATH):
    raise FileNotFoundError(
        f"Image classifier not found: {IMAGE_MODEL_PATH}"
    )

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

try:

    loaded_model = torch.load(
        IMAGE_MODEL_PATH,
        map_location=device,
        weights_only=False
    )

    if isinstance(
        loaded_model,
        torch.nn.Module
    ):

        image_model = loaded_model

    else:

        image_model = ProductClassifier(
            num_classes=10
        )

        if isinstance(loaded_model, dict):

            if "model_state_dict" in loaded_model:
                state_dict = loaded_model[
                    "model_state_dict"
                ]
            else:
                state_dict = loaded_model

            image_model.load_state_dict(
                state_dict
            )

except Exception as e:

    print(
        "Warning: Could not load image model automatically."
    )

    print(e)

    image_model = None


if image_model is not None:
    image_model.to(device)
    image_model.eval()


print(
    f"Image classifier device: {device}"
)


@tool
def classify_product_image(image_path: str) -> str:

    if image_model is None:
        return (
            "The product image classifier could not be loaded."
        )

    if not os.path.exists(image_path):
        return (
            f"Image file does not exist: {image_path}"
        )

    try:

        from torchvision import transforms

        transform = transforms.Compose([
            transforms.Grayscale(num_output_channels=3),
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]
            )
        ])

        image = Image.open(
            image_path
        ).convert("L")

        image_tensor = transform(
            image
        ).unsqueeze(0).to(device)

        with torch.no_grad():

            outputs = image_model(
                image_tensor
            )

            probabilities = torch.softmax(
                outputs,
                dim=1
            )

            confidence, predicted = torch.max(
                probabilities,
                dim=1
            )

        class_index = predicted.item()

        if class_index >= len(PRODUCT_CLASSES):
            return (
                "The model returned an unknown product class."
            )

        product_class = PRODUCT_CLASSES[
            class_index
        ]

        return (
            f"Predicted product category: "
            f"{product_class}\n"
            f"Confidence: {confidence.item():.2%}"
        )

    except Exception as e:

        return (
            "Unable to classify the image.\n"
            f"Error: {str(e)}"
        )


def create_llm():

    api_key = os.getenv(
        "OPENAI_API_KEY"
    )

    if not api_key:
        raise ValueError(
            "OPENAI_API_KEY environment variable is not set."
        )

    return ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0
    )


def create_support_agent():

    llm = create_llm()

    tools = [
        search_policy,
        check_return_risk,
        classify_product_image
    ]

    system_prompt = """
You are a Flipkart customer support assistant.

Your job is to provide accurate and helpful support.

Policy questions must be answered using the search_policy tool.

Never invent or assume a policy that is not present in the knowledge base.

If no relevant policy document is found, clearly say that the available knowledge base does not contain enough information.

Use check_return_risk whenever the user asks about the likelihood or risk of an order being returned.

Use classify_product_image whenever the user provides an image path and asks to identify or classify the product.

Do not hardcode return-risk predictions.

Do not hardcode image classification results.

Explain tool results clearly to the customer.

Keep answers concise, friendly, and professional.

If the user's question requires information that is unavailable, say so instead of making up an answer.
"""

    agent = create_react_agent(
        model=llm,
        tools=tools,
        prompt=system_prompt
    )

    return agent


def ask_agent(agent, question):

    result = agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content=question
                )
            ]
        }
    )

    messages = result["messages"]

    return messages[-1].content


def main():

    print("\n" + "=" * 70)
    print("FLIPKART SUPPORT ASSISTANT")
    print("=" * 70)

    print(
        "\nThe assistant can answer policy questions, "
        "check return risk, and classify product images."
    )

    agent = create_support_agent()

    while True:

        question = input(
            "\nYou: "
        ).strip()

        if question.lower() in [
            "exit",
            "quit",
            "bye"
        ]:

            print(
                "\nSupport Assistant: "
                "Thank you for contacting Flipkart support!"
            )

            break

        if not question:
            continue

        try:

            answer = ask_agent(
                agent,
                question
            )

            print(
                f"\nSupport Assistant: {answer}"
            )

        except Exception as e:

            print(
                "\nSupport Assistant: "
                f"Sorry, something went wrong: {e}"
            )


if __name__ == "__main__":
    main()